baseURL = "https://brandonjmatthews.github.io"
languageCode = 'en-us'
title = 'Brandon Matthews'
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-89861153-1"

theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.jpg"
  author = "Brandon Matthews"
  description = "This is my personal website."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

  favicon = true

[params.social]
  Github        = "brandonjmatthews"
  Email         = "brandonjmatthews@outlook.com"
  Twitter       = "_brandonjm"
  LinkedIn      = "brandonjmatthews"
  # Stackoverflow = "brandonjmatthews"
  Mastodon      = "@brandonjm"
  Orcid         = "0000-0002-8673-2434"
#   Medium        = "username"
#   Telegram      = "username"
#   RSS           = "/blog/index.xml"

## Main Menu
# [[menu.main]]
#   name = "blog"
#   weight = 100
#   identifier = "blog"
#   url = "/blog/"
  [[menu.main]]
  name = "publications"
  identifier = "publications"
  weight = 200
  url = "/publications/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 300
  url = "/projects/"
# [[menu.main]]
#   name = "CV"
#   identifier = "CV"
#   weight = 400
#   url = "/CV/"
